"""create worker domain models and ai_jobs

Revision ID: 226ecece29b1
Revises: acbf044165b1
Create Date: 2026-08-25 17:18:26.068033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '226ecece29b1'
down_revision: Union[str, Sequence[str], None] = 'acbf044165b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_jobs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', name='aijobstatus', native_enum=False, length=20), nullable=False),
    sa.Column('intent', sa.Enum('TASK', 'SCHEDULE', 'MEMO', 'RESEARCH', name='intent', native_enum=False, length=20), nullable=True),
    sa.Column('result_ref_type', sa.String(length=50), nullable=True),
    sa.Column('result_ref_id', sa.Uuid(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_jobs_celery_task_id', 'ai_jobs', ['celery_task_id'], unique=False)
    op.create_index('ix_ai_jobs_user_id_created_at', 'ai_jobs', ['user_id', 'created_at'], unique=False)
    op.create_table('memos',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memos_user_id_created_at', 'memos', ['user_id', 'created_at'], unique=False)
    op.create_table('schedules',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedules_user_id_created_at', 'schedules', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_schedules_user_id_start_at', 'schedules', ['user_id', 'start_at'], unique=False)
    op.create_table('tasks',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='taskstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_user_id_created_at', 'tasks', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_tasks_user_id_due_date', 'tasks', ['user_id', 'due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_user_id_due_date', table_name='tasks')
    op.drop_index('ix_tasks_user_id_created_at', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_schedules_user_id_start_at', table_name='schedules')
    op.drop_index('ix_schedules_user_id_created_at', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index('ix_memos_user_id_created_at', table_name='memos')
    op.drop_table('memos')
    op.drop_index('ix_ai_jobs_user_id_created_at', table_name='ai_jobs')
    op.drop_index('ix_ai_jobs_celery_task_id', table_name='ai_jobs')
    op.drop_table('ai_jobs')
    # ### end Alembic commands ###
